// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEWA3KTaSxYLIvHF7Uuqv734j3_hTMUQ',
    appId: '1:797421387226:web:df314bb752f4e7c35494e3',
    messagingSenderId: '797421387226',
    projectId: 'neurova-4a0b4',
    authDomain: 'neurova-4a0b4.firebaseapp.com',
    storageBucket: 'neurova-4a0b4.firebasestorage.app',
    measurementId: 'G-FTLS8VTXKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEM6d0iZihtkVPkp3nvxPlRG9WHCaCx_4',
    appId: '1:797421387226:android:9f8413b0abb5461e5494e3',
    messagingSenderId: '797421387226',
    projectId: 'neurova-4a0b4',
    storageBucket: 'neurova-4a0b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3cr9mJiMQD1WlS2vxo10bEpb56OTfid0',
    appId: '1:797421387226:ios:7ff8c92f9906a52a5494e3',
    messagingSenderId: '797421387226',
    projectId: 'neurova-4a0b4',
    storageBucket: 'neurova-4a0b4.firebasestorage.app',
    iosClientId: '797421387226-kbgud8u6af1t7o3di3vpst1hnm79t9nb.apps.googleusercontent.com',
    iosBundleId: 'com.neurova.app',
  );
}
